apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  type: LoadBalancer           # expose publicly on the internet
  selector:
    app: iris-api
  ports:
    - port: 80
      targetPort: 8000
